# Generated by Django 4.1.3 on 2024-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
