# Generated by Django 4.1.3 on 2024-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_sub_category_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
