# Generated by Django 4.1.3 on 2024-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sub_category_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
