# Generated by Django 4.1.3 on 2024-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quesmodel_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='course',
            field=models.CharField(blank=True, default='Nec', max_length=200, null=True),
        ),
    ]
