# Generated by Django 4.1.3 on 2024-02-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_category_course_subject_category_subject'),
        ('quiz', '0004_quesmodel_course_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course'),
        ),
    ]
